ValidataTestWebApplication/Controllers/AddCustomerController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using ValidataTest.Core.DAL;
using ValidataTest.Core.Models;
using ValidataTestWebApplication.Models;

namespace ValidataTestWebApplication.Controllers
{
    public class AddCustomerController : Controller
    {
        /// <summary>
        /// For deleting demonstration. Not the best decision
        /// </summary>
        internal static int LastAddedID = 0;

        // GET: AddCustomer
        public async Task<ActionResult> Index()
        {
            UnitOfWork unitOfWork = new UnitOfWork();
            var customer = new Customer("test Name", "test LastName", "test Address", "test Code", null);
            var result = await unitOfWork.CreateCustomerAsync(customer);
            LastAddedID = customer.CustomerID;
            return View(new AsyncDbTaskResultForCreate() { NewId = customer.CustomerID, TaskResult = result });
        }
    }
}

ValidataTestWebApplication/Controllers/AddOrderController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using System.Web.Mvc;
using ValidataTest.Core.DAL;
using ValidataTest.Core.Models;
using ValidataTestWebApplication.Models;

namespace ValidataTestWebApplication.Controllers
{
    public class AddOrderController : Controller
    {
        // GET: AddOrder
        public async Task<ActionResult> Index()
        {
            UnitOfWork unitOfWork = new UnitOfWork();
            var order = new Order(DateTime.Now, AddCustomerController.LastAddedID, null,
                    new ReadOnlyCollection<Item>(
                        new List<Item>()
                        {
                            new Item(10f, 1, null, 0, null),
                            new Item(01f, 2, null, 0, null)
                        }));
            var result = await unitOfWork.CreateOrderAsync(order);
            return View(new AsyncDbTaskResultForCreate() { NewId = order.OrderId, TaskResult = result });
        }
    }
}

ValidataTestWebApplication/Controllers/DeleteCustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ValidataTest.Core.DAL;
using ValidataTest.Core.Models;
using ValidataTestWebApplication.Models;

namespace ValidataTestWebApplication.Controllers
{
    public class DeleteCustomerController : Controller
    {
        // GET: DeleteCustomer
        public async Task<ActionResult> Index()
        {
            UnitOfWork unitOfWork = new UnitOfWork();
            var customer = new Customer("test Name", "test LastName", "test Address", "test Code", null) 
                { CustomerID = AddCustomerController.LastAddedID };
            var result = await unitOfWork.DeleteCustomerAsync(customer);
            return View(new AsyncDbTaskResult() { TaskResult = result });
        }
    }
}

ValidataTestWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Validata Test Web Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <nav>
                    <ul id="menu" style="font-size:larger">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    </ul>
                    <h4>Direct database calls</h4>
                    <ul id="menu" style="font-size:larger">
                        <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                        <li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                        <li>@Html.ActionLink("Items", "Index", "Items")</li>
                        <li>@Html.ActionLink("Products", "Index", "Products")</li>
                    </ul>
                    <h4>Public API</h4>
                    <ul id="menu" style="font-size:larger">
                        <li>@Html.ActionLink("Add pre-made Customer (CreateCustomerAsync)", "Index", "AddCustomer")</li>
                        <li>@Html.ActionLink("Add pre-made Order to newly added Customer (CreateOrderAsync)", "Index", "AddOrder")</li>
                        <li>@Html.ActionLink("Delete newly added Customer with his/her Orders (DeleteCustomerAsync)", "Index", "DeleteCustomer")</li>
                    </ul>
                </nav>
            </div>
            <div class="float-right">

            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - Validata</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>